2023-12-19 08:23:18.169 | INFO     | scripts.pipeline_ai:<module>:27 - Running on darwin
2023-12-19 08:23:18.170 | INFO     | scripts.pipeline_class:process:190 - hindi process started
2023-12-19 08:23:18.170 | INFO     | scripts.pipeline_class:__init__:33 - Class initialized
2023-12-19 08:23:18.170 | INFO     | scripts.pipeline_class:__init__:39 - Device: cpu
2023-12-19 08:23:18.170 | INFO     | scripts.pipeline_class:start:117 - Starting Pipeline
2023-12-19 08:23:18.170 | INFO     | scripts.pipeline_class:translated_sub:68 - Creating Subtitles
2023-12-19 08:23:18.170 | INFO     | scripts.pipeline_class:translated_sub:73 - Reaching out to translator function...
2023-12-19 08:25:34.162 | ERROR    | scripts.pipeline_class:translate:49 - Error occurred while loading the model/tokenizer: (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /repos/6e/ef/6eef128ace768b50a05cfccb07249581231dafe7b91ae38b6d142cbc66dab00d/c266c2cfd19758b6d09c1fc31ecdf1e485509035f6b51dfe84f1ada83eefcc42?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27pytorch_model.bin%3B+filename%3D%22pytorch_model.bin%22%3B&response-content-type=application%2Foctet-stream&Expires=1703213601&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMzIxMzYwMX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy82ZS9lZi82ZWVmMTI4YWNlNzY4YjUwYTA1Y2ZjY2IwNzI0OTU4MTIzMWRhZmU3YjkxYWUzOGI2ZDE0MmNiYzY2ZGFiMDBkL2MyNjZjMmNmZDE5NzU4YjZkMDljMWZjMzFlY2RmMWU0ODU1MDkwMzVmNmI1MWRmZTg0ZjFhZGE4M2VlZmNjNDI~cmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIn1dfQ__&Signature=WW7loc2fzV8QvVK7RvC8wyoeRcmP6VLongeVW7Iv2eB9Ul~CAMKMDG3sQgRtQDemLN8UFIvPWbOaXWMjYLqd~tILugPuk5yjoPgRRZmi2ddIaKDL3nBTx2oZeq4UnK9~ERvGzV4JjskY~lGDWHBcbKkUqi7I5EV-SbKQxscYkUVR~LdFxfWAgVcDh2IrpI2rObvWu-aDfCBsbRAjXRywbWx4p9ZgvgUcP3~6pKT92HjjBncYL7Fghx3xuWzWyzOcEv3xzOH6MhkUTY0h75jAf~-KAu-mMT8axbTRqwAYoUazRwNvb~eNbr-ZBEUE2rFQfGYEwL-WLSWB1xwV5PTUlw__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x28be94670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))"), '(Request ID: 9ae71ecc-c2b8-4616-9234-995b2e205ff4)')
2023-12-19 08:25:34.163 | ERROR    | scripts.pipeline_class:translated_sub:90 - Error while translating subtitles:1
2023-12-19 08:25:34.163 | ERROR    | scripts.pipeline_class:start:131 - Error while running pipeline:1
