2023-12-19 08:41:28.183 | INFO     | scripts.pipeline_class:<module>:28 - Running on darwin
2023-12-19 08:41:28.186 | INFO     | scripts.pipeline_ai:<module>:27 - Running on darwin
2023-12-19 08:41:28.186 | INFO     | scripts.pipeline_class:process:190 - hindi process started
2023-12-19 08:41:28.187 | INFO     | scripts.pipeline_class:__init__:33 - Class initialized
2023-12-19 08:41:28.187 | INFO     | scripts.pipeline_class:__init__:39 - Device: cpu
2023-12-19 08:41:28.187 | INFO     | scripts.pipeline_class:start:117 - Starting Pipeline
2023-12-19 08:41:28.187 | INFO     | scripts.pipeline_class:translated_sub:68 - Creating Subtitles
2023-12-19 08:41:28.187 | INFO     | scripts.pipeline_class:translated_sub:73 - Reaching out to translator function...
2023-12-19 08:44:14.963 | ERROR    | scripts.pipeline_class:translate:49 - Error occurred while loading the model/tokenizer: (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /repos/6e/ef/6eef128ace768b50a05cfccb07249581231dafe7b91ae38b6d142cbc66dab00d/c266c2cfd19758b6d09c1fc31ecdf1e485509035f6b51dfe84f1ada83eefcc42?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27pytorch_model.bin%3B+filename%3D%22pytorch_model.bin%22%3B&response-content-type=application%2Foctet-stream&Expires=1703214691&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMzIxNDY5MX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy82ZS9lZi82ZWVmMTI4YWNlNzY4YjUwYTA1Y2ZjY2IwNzI0OTU4MTIzMWRhZmU3YjkxYWUzOGI2ZDE0MmNiYzY2ZGFiMDBkL2MyNjZjMmNmZDE5NzU4YjZkMDljMWZjMzFlY2RmMWU0ODU1MDkwMzVmNmI1MWRmZTg0ZjFhZGE4M2VlZmNjNDI~cmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIn1dfQ__&Signature=WyF3kPav-CBEDoW3N9Zc2fvXZCQxe2Nz67Hq5D5CNfOde-TRyMcU0EIODg4hDxU7QiSiG9D31~BQ6V8D1XnQeFyJtmyZwK3Ydqhj32Z~gB5lbf9u5Bs8wLzGp4BFZuyyINIPolGXTKSkkrxgQz-sU3KzMvkV4MpcKBYqRH1pgk2XQBccoyvYsFSp9ccyhE~Vc2rbmVFdJWnWMomN1--LBtK~aWdGGXxa-KIIDsfc9OwpPrAUELP1jiotwIz48xlrB~Zjo-cxEfZzn2WDedx0OtNgcs2~3vXqkVd2ARhlB8dyMOcSicoS8zx5D-Th~r6bFpYLhvaYNbztqtEAnyF-hg__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x29e1e4610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))"), '(Request ID: 71148fac-ebdd-4f1b-b17c-9a422e5b830a)')
2023-12-19 08:44:14.971 | ERROR    | scripts.pipeline_class:translated_sub:90 - Error while translating subtitles:1
2023-12-19 08:44:14.972 | ERROR    | scripts.pipeline_class:start:131 - Error while running pipeline:1
